### ISSUE TITLE
Setting font in XML?

### ISSUE THREAD

**Issue by gouravd** [AnwarShahriar/Calligrapher#1]
Is there a way currently to set the font directly in the XML (like the Calligraphy?)

**Comment by AnwarShahriar** [comment]
@gouravd  Currently there is no way to set the font directly in XML. I'll look into that and making it an enhancement request. Thanks.

**Comment by AnwarShahriar** [comment]
As it seems Android Databinding Library is doing a great job with this type of thing. This enhancement will not be included in any future release. I'll strongly suggest to use Android Databinding library if you want a great way to add font from XML. Binding adapter in databinding library will help you to achieve this thing in your entire application with minimal effort.
