### ISSUE TITLE
Font in custom Dialog 

### ISSUE THREAD

**Issue by sammyrocz** [AnwarShahriar/Calligrapher#3]
Could you please tell me how to set font in custom DialogFragment

**Comment by AnwarShahriar** [comment]
Before returning you view from `onCreateView` do the following,
```java
Calligrapher calligrapher = new Calligrapher(this);
calligrapher.setFont(your_inflated_view, path_to_your_font_in_asset_directory);
```
Let me know if you face any difficulty.
